export const clothingProducts = [
  {
    id: 1,
    name: "T-shirt",
    color: "White",
    size: "M",
    material: "Cotton",
    price: 15.99,
  },
  {
    id: 2,
    name: "Jeans",
    color: "Blue",
    size: "32x32",
    material: "Denim",
    price: 29.99,
  },
  {
    id: 3,
    name: "Hoodie",
    color: "Gray",
    size: "L",
    material: "Fleece",
    price: 39.99,
  },
  {
    id: 4,
    name: "Dress Shirt",
    color: "Light Blue",
    size: "15.5",
    material: "Cotton",
    price: 24.99,
  },
  {
    id: 5,
    name: "Sneakers",
    color: "Black",
    size: "10",
    material: "Canvas",
    price: 49.99,
  },
  {
    id: 6,
    name: "Skirt",
    color: "Red",
    size: "S",
    material: "Polyester",
    price: 19.99,
  },
  {
    id: 7,
    name: "Sweater",
    color: "Green",
    size: "XL",
    material: "Wool",
    price: 34.99,
  },
  {
    id: 8,
    name: "Dress",
    color: "Black",
    size: "M",
    material: "Silk",
    price: 59.99,
  },
  {
    id: 9,
    name: "Shorts",
    color: "Khaki",
    size: "36",
    material: "Cotton",
    price: 22.99,
  },
  {
    id: 10,
    name: "Jacket",
    color: "Navy",
    size: "L",
    material: "Polyester",
    price: 44.99,
  },
];
